version: '3'
services:
  comparedns:
    image: compare_dns
    container_name: CompareDNS
    env_file: .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
